version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    working_dir: /app
    ports:
      - "3001:3001"
    command: npm start
